export const profileStyles = {
	container: {
		bgcolor: "primary.main",
		width: 1,
		display: "flex",
		flexDirection: "column",
	},
	header: {
		padding: "20px 1.2rem",
		display: "flex",
		alignItems: "center",
		color: "white",
		justifyContent: "space-between",
	},
	title: {
		fontWeight: "bold",
		color: "white",
		letterSpacing: 3,
	},
	body: {
		height: "auto",
		width: 1,
		flexGrow: 1,
		bgcolor: "white",
		display: "flex",
		flexDirection: "column",
		borderRadius: "25px 25px 0 0",
		padding: " 0 1.2rem ",
		boxShadow: "rgba(0, 0, 0, 0.56) 0px 22px 70px 12px",
	},
	cardContainer: {
		padding: 2,
		width: 1,
		bgcolor: "secondary.light",
		borderRadius: "1rem",
		display: "flex",
		flexDirection: "column",
		mb: "2rem",
		gap: 2,
	},
	bodyTitle: {
		fontWeight: "bold",
		color: "primary.main",
		margin: "30px 0px 10px",
	},
};
